<?php

/**
 * Defines available languages for highlighting
 */

return [
    ['name' => 'Markdown', 'value' => 'markdown'],
    ['name' => 'Markdown (GitHub-flavour)', 'value' => 'gfm'],
    ['name' => 'Shell', 'value' => 'shell'],
    ['name' => 'CSS', 'value' => 'css'],
    ['name' => 'HTML', 'value' => 'htmlmixed'],
    ['name' => 'JavaScript', 'value' => 'javascript'],
    ['name' => 'PHP', 'value' => 'php'],
    ['name' => 'SQL', 'value' => 'sql'],
    ['name' => 'C-like', 'value' => 'clike'],
    ['name' => 'APL', 'value' => 'apl'],
    ['name' => 'PGP (ASCII armor)', 'value' => 'asciiarmor'],
    ['name' => 'ASN.1', 'value' => 'asn.1'],
    ['name' => 'Asterisk dialplan', 'value' => 'asterisk'],
    ['name' => 'Brainfuck', 'value' => 'brainfuck'],
    ['name' => 'C/C++/C#', 'value' => 'clike'],
    ['name' => 'Ceylon', 'value' => 'clike'],
    ['name' => 'Clojure', 'value' => 'clojure'],
    ['name' => 'CMake', 'value' => 'cmake'],
    ['name' => 'Cobol', 'value' => 'cobol'],
    ['name' => 'CoffeeScript', 'value' => 'coffeescript'],
    ['name' => 'Common Lisp', 'value' => 'commonlisp'],
    ['name' => 'Crystal', 'value' => 'crystal'],
    ['name' => 'Cypher', 'value' => 'cypher'],
    ['name' => 'D', 'value' => 'd'],
    ['name' => 'Dart', 'value' => 'dart'],
    ['name' => 'Diff', 'value' => 'diff'],
    ['name' => 'Django', 'value' => 'django'],
    ['name' => 'Dockerfile', 'value' => 'dockerfile'],
    ['name' => 'DTD', 'value' => 'dtd'],
    ['name' => 'Dylan', 'value' => 'dylan'],
    ['name' => 'EBNF', 'value' => 'ebnf'],
    ['name' => 'ECL', 'value' => 'ecl'],
    ['name' => 'Eiffel', 'value' => 'eiffel'],
    ['name' => 'Elm', 'value' => 'elm'],
    ['name' => 'Erlang', 'value' => 'erlang'],
    ['name' => 'F#', 'value' => 'mllike'],
    ['name' => 'Factor', 'value' => 'factor'],
    ['name' => 'FCL', 'value' => 'fcl'],
    ['name' => 'Forth', 'value' => 'forth'],
    ['name' => 'Fortran', 'value' => 'fortran'],
    ['name' => 'Gas', 'value' => 'gas'],
    ['name' => 'Gherkin', 'value' => 'gherkin'],
    ['name' => 'Go', 'value' => 'go'],
    ['name' => 'Groovy', 'value' => 'groovy'],
    ['name' => 'HAML', 'value' => 'haml'],
    ['name' => 'Handlebars', 'value' => 'handlebars'],
    ['name' => 'Haskell', 'value' => 'haskell'],
    ['name' => 'Literate', 'value' => 'haskell-literate'],
    ['name' => 'Haxe', 'value' => 'haxe'],
    ['name' => 'HTTP', 'value' => 'http'],
    ['name' => 'IDL', 'value' => 'idl'],
    ['name' => 'Java', 'value' => 'clike'],
    ['name' => 'Jinja2', 'value' => 'jinja2'],
    ['name' => 'JSX', 'value' => 'jsx'],
    ['name' => 'Julia', 'value' => 'julia'],
    ['name' => 'Kotlin', 'value' => 'clike'],
    ['name' => 'LaTeX', 'value' => 'stex'],
    ['name' => 'LESS', 'value' => 'css'],
    ['name' => 'LiveScript', 'value' => 'livescript'],
    ['name' => 'Lua', 'value' => 'lua'],
    ['name' => 'Mathematica', 'value' => 'mathematica'],
    ['name' => 'mbox', 'value' => 'mbox'],
    ['name' => 'mIRC', 'value' => 'mirc'],
    ['name' => 'Modelica', 'value' => 'modelica'],
    ['name' => 'MscGen', 'value' => 'mscgen'],
    ['name' => 'MUMPS', 'value' => 'mumps'],
    ['name' => 'Nginx', 'value' => 'nginx'],
    ['name' => 'NSIS', 'value' => 'nsis'],
    ['name' => 'N-Triples/N-Quads', 'value' => 'ntriples'],
    ['name' => 'Objective-C', 'value' => 'clike'],
    ['name' => 'OCaml', 'value' => 'mllike'],
    ['name' => 'Octave', 'value' => 'octave'],
    ['name' => 'Oz', 'value' => 'oz'],
    ['name' => 'Pascal', 'value' => 'pascal'],
    ['name' => 'PEG.js', 'value' => 'pegjs'],
    ['name' => 'Perl', 'value' => 'perl'],
    ['name' => 'Pig Latin', 'value' => 'pig'],
    ['name' => 'PowerShell', 'value' => 'powershell'],
    ['name' => 'Properties', 'value' => 'properties'],
    ['name' => 'ProtoBuf', 'value' => 'protobuf'],
    ['name' => 'Pug', 'value' => 'pug'],
    ['name' => 'Puppet', 'value' => 'puppet'],
    ['name' => 'Python', 'value' => 'python'],
    ['name' => 'Q', 'value' => 'q'],
    ['name' => 'R', 'value' => 'r'],
    ['name' => 'RPM', 'value' => 'rpm'],
    ['name' => 'reStructuredText', 'value' => 'rst'],
    ['name' => 'Ruby', 'value' => 'ruby'],
    ['name' => 'Rust', 'value' => 'rust'],
    ['name' => 'SAS', 'value' => 'sas'],
    ['name' => 'Sass', 'value' => 'sass'],
    ['name' => 'Scheme', 'value' => 'scheme'],
    ['name' => 'Sieve', 'value' => 'sieve'],
    ['name' => 'Slim', 'value' => 'slim'],
    ['name' => 'Smalltalk', 'value' => 'smalltalk'],
    ['name' => 'Smarty', 'value' => 'smarty'],
    ['name' => 'Solr', 'value' => 'solr'],
    ['name' => 'Soy', 'value' => 'soy'],
    ['name' => 'SPARQL', 'value' => 'sparql'],
    ['name' => 'Spreadsheet', 'value' => 'spreadsheet'],
    ['name' => 'sTeX', 'value' => 'stex'],
    ['name' => 'Stylus', 'value' => 'stylus'],
    ['name' => 'Swift', 'value' => 'swift'],
    ['name' => 'Tcl', 'value' => 'tcl'],
    ['name' => 'Textile', 'value' => 'textile'],
    ['name' => 'Tiddlywiki', 'value' => 'tiddlywiki'],
    ['name' => 'Tiki wiki', 'value' => 'tiki'],
    ['name' => 'TOML', 'value' => 'toml'],
    ['name' => 'Tornado', 'value' => 'tornado'],
    ['name' => 'troff', 'value' => 'troff'],
    ['name' => 'TTCN', 'value' => 'ttcn'],
    ['name' => 'TTCN Configuration', 'value' => 'ttcn-cfg'],
    ['name' => 'Turtle', 'value' => 'turtle'],
    ['name' => 'Twig', 'value' => 'twig'],
    ['name' => 'VB.NET', 'value' => 'vb'],
    ['name' => 'VBScript', 'value' => 'vbscript'],
    ['name' => 'Velocity', 'value' => 'velocity'],
    ['name' => 'Verilog', 'value' => 'verilog'],
    ['name' => 'VHDL', 'value' => 'vhdl'],
    ['name' => 'Vue.js', 'value' => 'vue'],
    ['name' => 'WebAssembly Text Format', 'value' => 'wast'],
    ['name' => 'Web IDL', 'value' => 'webidl'],
    ['name' => 'XML', 'value' => 'xml'],
    ['name' => 'XQuery', 'value' => 'xquery'],
    ['name' => 'Yacas', 'value' => 'yacas'],
    ['name' => 'YAML', 'value' => 'yaml'],
    ['name' => 'YAML frontmatter', 'value' => 'yaml-frontmatter'],
    ['name' => 'Z80', 'value' => 'z80'],
];
